package Glowne;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Szab
 */
import javax.swing.DefaultListModel;

public class SimulationGUI extends javax.swing.JFrame
{
    private MemoryManager ProcMan = null;
    private IOController IO = null;

    /**
     * Creates new form SimulationGUI
     */
    
    // Dodatkowy konstruktor
    public SimulationGUI(MemoryManager ProcMan, IOController IO)
    {
        this.ProcMan = ProcMan;
        
        this.IO = IO;
        initComponents();
        
       // Integer count = ProcMan._templateList.size();
       // lblGeneratorCount.setText(count.toString());  
       // lblROTQuant.setText((new Integer(ProcMan.quantSize)).toString());
        
    }
    
    public SimulationGUI()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        canvas1 = new java.awt.Canvas();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblIloscPrzebiegow = new javax.swing.JLabel();
        lblRemaining = new javax.swing.JLabel();
        lblRealised = new javax.swing.JLabel();
        lblErrors = new javax.swing.JLabel();
        lblErrPerPage = new javax.swing.JLabel();
        lblPages = new javax.swing.JLabel();
        lblRamki = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnNextQ = new javax.swing.JButton();
        btnFastFW = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstPages = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstWywolania = new javax.swing.JList();
        jScrollPane5 = new javax.swing.JScrollPane();
        lstProcesy = new javax.swing.JList();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstSegmenty = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Statystyki symulacji"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Pozostało odwołań:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 46, -1, -1));

        jLabel3.setText("Zrealizowano odwołań:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 66, -1, -1));

        jLabel4.setText("Ilość błędów:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 86, -1, -1));

        jLabel6.setText("Błędów na stronę:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 138, -1, -1));

        jLabel7.setText("Ilość stron:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 158, -1, -1));

        jLabel8.setText("Ilość przebiegów:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 27, -1, -1));

        jLabel11.setText("Ilość ramek:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 178, -1, -1));

        lblIloscPrzebiegow.setText("0");
        jPanel1.add(lblIloscPrzebiegow, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 27, -1, -1));

        lblRemaining.setText("0");
        jPanel1.add(lblRemaining, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 46, -1, -1));

        lblRealised.setText("0");
        jPanel1.add(lblRealised, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 66, -1, -1));

        lblErrors.setText("0");
        jPanel1.add(lblErrors, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 86, -1, -1));

        lblErrPerPage.setText("0,0");
        jPanel1.add(lblErrPerPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 138, -1, -1));

        lblPages.setText("0");
        jPanel1.add(lblPages, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 158, -1, -1));

        lblRamki.setText("0");
        jPanel1.add(lblRamki, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 178, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 360, 220));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Kontrola przebiegu"));

        btnNextQ.setText("Nastepne odwolanie");
        btnNextQ.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnNextQActionPerformed(evt);
            }
        });

        btnFastFW.setText("Przejdź do końca");
        btnFastFW.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnFastFWActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNextQ, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(btnFastFW, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNextQ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFastFW)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 180, -1));

        jScrollPane3.setViewportView(lstPages);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 490, 130));

        jScrollPane4.setViewportView(lstWywolania);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 480, 240));

        lstProcesy.addListSelectionListener(new javax.swing.event.ListSelectionListener()
        {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt)
            {
                lstProcesyValueChanged(evt);
            }
        });
        jScrollPane5.setViewportView(lstProcesy);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 490, 110));

        jScrollPane1.setViewportView(lstSegmenty);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 970, 130));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextQActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnNextQActionPerformed
    {//GEN-HEADEREND:event_btnNextQActionPerformed
        ProcMan.nextStep();
    }//GEN-LAST:event_btnNextQActionPerformed

    private void btnFastFWActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnFastFWActionPerformed
    {//GEN-HEADEREND:event_btnFastFWActionPerformed
        ProcMan.endSimulation();
    }//GEN-LAST:event_btnFastFWActionPerformed

    private void lstProcesyValueChanged(javax.swing.event.ListSelectionEvent evt)//GEN-FIRST:event_lstProcesyValueChanged
    {//GEN-HEADEREND:event_lstProcesyValueChanged
        if(lstProcesy.getSelectedIndex() != -1)
        {
        Process proc = ProcMan.processList.get(lstProcesy.getSelectedIndex());
        DefaultListModel tmplmodel = new DefaultListModel();
        for(int i = 0 ; i<proc.callList.length ; i++)
        {
            Page page = proc.callList[i];
                tmplmodel.addElement("Właściciel strony: "+page.owner.id+", czy w pamięci: "+page.presenceBit+", adres segmentu: "+page.segmentNumber);
        }
        lstPages.setModel(tmplmodel);
        }
    }//GEN-LAST:event_lstProcesyValueChanged

    // Ustawia wartosc wygenerowanych procesów
    /*
    public void incrementGenerated()
    {
        Integer count = Integer.parseInt(lblCountGenerated.getText());
        count += 1;
        
        lblCountGenerated.setText(count.toString());
    }
    */
    
    // Aktualizuje wartości statystyk
    public void update()
    {
        lblErrors.setText(ProcMan.sumErrors()+"");
        lblIloscPrzebiegow.setText(""+ProcMan.workTime);
        lblErrPerPage.setText(""+ProcMan.getErrorsPerPage());
        lblPages.setText(""+ProcMan.sumPages());
        lblRamki.setText(""+ProcMan.memory.segments.length);
        lblRealised.setText(""+ProcMan.callHistory.size());
        lblRemaining.setText(""+ProcMan.ciagOdwolan.size());
        
        // Zapełnienie listy segmentów
        DefaultListModel mdl = new DefaultListModel();
        for(int i = 0 ; i<ProcMan.memory.segments.length ; i++)
        {
            Page[] segments = ProcMan.memory.segments;
            if(segments[i] == null)
            {
                mdl.addElement(i+". Wpis pusty");
            }
            else
            {
                mdl.addElement(i+". Właściciel strony: "+segments[i].owner.id);
            }
        }
       lstSegmenty.setModel(mdl);
        
        // Zapełnienie listy procesów
        DefaultListModel model = new DefaultListModel();
        int selected = 0;
        
        if(!ProcMan.processList.isEmpty())
        {
            for(Process process : ProcMan.processList)
            {
                model.addElement(process.id);
            }
        }
        else
        {
            model.addElement("Brak procesów");
        }
        lstProcesy.setModel(model);
        if(!lstProcesy.isSelectedIndex(selected))
        lstProcesy.setSelectedIndex(selected);  
        
         // Zapełnienie listy wywołań
        DefaultListModel tmplmodel = new DefaultListModel();
        if(ProcMan.ciagOdwolan.size()!=0)
        {
            for(Page page : ProcMan.ciagOdwolan)
            {
                tmplmodel.addElement("Właściciel strony: "+page.owner.id+", czy w pamięci: "+page.presenceBit+", adres segmentu: "+page.segmentNumber);
            }
        }
        else
        {
            tmplmodel.addElement("Brak stron do wywolania");
        }
        lstWywolania.setModel(tmplmodel);
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFastFW;
    private javax.swing.JButton btnNextQ;
    private java.awt.Canvas canvas1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblErrPerPage;
    private javax.swing.JLabel lblErrors;
    private javax.swing.JLabel lblIloscPrzebiegow;
    private javax.swing.JLabel lblPages;
    private javax.swing.JLabel lblRamki;
    private javax.swing.JLabel lblRealised;
    private javax.swing.JLabel lblRemaining;
    private javax.swing.JList lstPages;
    private javax.swing.JList lstProcesy;
    private javax.swing.JList lstSegmenty;
    private javax.swing.JList lstWywolania;
    // End of variables declaration//GEN-END:variables
}
